---
meta:
  git:
    owner: someco
    repo:  something-deployments
    private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      lol. you didn't really think that
      we'd put the key here, in a test,
      did you?!
      -----END RSA PRIVATE KEY-----

  slack:
    channel: '#botspam'
    webhook: http://127.0.0.1:1337
